name: Flatpak

on:
  push:
  pull_request:

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          "submodules": true
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: io.github.smolblackcat.Progress.Devel.json
          bundle: progress.flatpak
          run-tests: true
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: true
