name: Progress CI

on: ["push", "pull_request"]

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4

      - name: Setup UCRT64 Environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-python
            mingw-w64-ucrt-x86_64-gtkmm4
            mingw-w64-ucrt-x86_64-libadwaita
            mingw-w64-ucrt-x86_64-tinyxml2
            mingw-w64-ucrt-x86_64-gettext
            mingw-w64-ucrt-x86_64-catch
            mingw-w64-ucrt-x86_64-spdlog
            mingw-w64-ucrt-x86_64-nsis
            git

      - name: Build
        run: |
          cmake -GNinja -B build -DDEVELOPMENT=ON
          cmake --build build

      - name: Test
        run: |
          cd build/
          ctest

  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch Dependencies
        run: |
          sudo apt install libgtkmm-4.0-dev
          sudo apt install libadwaita-1-dev
          sudo apt install libtinyxml2-dev
          sudo apt install libspdlog-dev
          sudo apt install gettext
          sudo apt install catch2

      - name: Build
        run: |
          cmake -B ${{github.workspace}}/build -DDEVELOPMENT=ON -DCMAKE_CXX_COMPILER=g++-14
          cmake --build ${{github.workspace}}/build

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest

  flatpak:
    name: "Flatpak"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Setup Environment"
        run: |
          sudo apt install flatpak-builder flatpak
          flatpak install runtime/org.gnome.Sdk/x86_64/47
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
        with:
          bundle: progress.flatpak
          manifest-path: io.github.smoblackcat.Progress.Devel.json
          cache-key: flatpak-builder-${{ github.sha }}
          run-tests: true
