name: Progress CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        development-modes: [ON, OFF]

    defaults:
      run:
        shell: msys2 {0}  # Default shell for Windows

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            echo "Setting up MSYS2 environment..."
            # Setup for Windows
            uses: msys2/setup-msys2@v2
            with:
              msystem: UCRT64
              update: true
              install: |
                mingw-w64-ucrt-x86_64-gcc
                mingw-w64-ucrt-x86_64-cmake
                mingw-w64-ucrt-x86_64-python
                mingw-w64-ucrt-x86_64-gtkmm4
                mingw-w64-ucrt-x86_64-libadwaita
                mingw-w64-ucrt-x86_64-tinyxml2
                mingw-w64-ucrt-x86_64-gettext
                mingw-w64-ucrt-x86_64-catch
                mingw-w64-ucrt-x86_64-spdlog
                mingw-w64-ucrt-x86_64-nsis
                git
          else
            echo "Installing dependencies for Linux..."
            sudo apt update
            sudo apt install -y libgtkmm-4.0-dev libadwaita-1-dev libtinyxml2-dev libspdlog-dev gettext catch2
          fi

      - name: Build
        run: |
          git submodule update --init
          cmake -B build -DDEVELOPMENT=${{ matrix.development-modes }} -DCMAKE_CXX_COMPILER=g++-14
          cmake --build build

      - name: Test
        run: |
          cd build/
          ctest

      - name: Setup Artifacts
        run: |
          cd build/
          mkdir dev-build
          cpack
          mv *.exe dev-build/ || true
          mv *.deb dev-build/ || true
          mv *.tar.xz dev-build/ || true
          if [ "${{ matrix.development-modes }}" == "ON" ]; then
            echo "FILENAME=devel" >> $GITHUB_ENV
          else
            echo "FILENAME=prod" >> $GITHUB_ENV
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ env.FILENAME }}-build
          path: build/dev-build/

